import React, { Component } from "react";
import {
  StyleSheet,
  View,
  Text,
  ScrollView,
  TouchableOpacity
} from "react-native";

export default class PrivacyPolicyScreen extends Component {
  static navigationOptions = {
    header: null
  };

  render() {
    return (
      <ScrollView>
        <View style={styles.container}>
          <Text style={styles.subheaderText}>Privacy Policy </Text>
          <Text style={styles.policyText}>
            Your privacy is important to us. It is Safe Street Riderz's policy
            to respect your privacy regarding any information we may collect
            from you through our app, Street Ride.
          </Text>
          <Text style={styles.policyText}>
            We only ask for personal information when we truly need it to
            provide a service to you. We collect it by fair and lawful means,
            with your knowledge and consent. We also let you know why we’re
            collecting it and how it will be used.
          </Text>
          <Text style={styles.policyText}>
            We only retain collected information for as long as necessary to
            provide you with your requested service. What data we store, we’ll
            protect within commercially acceptable means to prevent loss and
            theft, as well as unauthorised access, disclosure, copying, use or
            modification.
          </Text>
          <Text style={styles.policyText}>
            We don’t share any personally identifying information publicly or
            with third-parties, except when required to by law.
          </Text>
          <Text style={styles.policyText}>
            Our app may link to external sites that are not operated by us.
            Please be aware that we have no control over the content and
            practices of these sites, and cannot accept responsibility or
            liability for their respective privacy policies.
          </Text>
          <Text style={styles.policyText}>
            You are free to refuse our request for your personal information,
            with the understanding that we may be unable to provide you with
            some of your desired services.
          </Text>
          <Text style={styles.policyText}>
            Your continued use of our website will be regarded as acceptance of
            our practices around privacy and personal information. If you have
            any questions about how we handle user data and personal
            information, feel free to contact us.
          </Text>
          <Text style={styles.policyText}>
            This policy is effective as of May 1, 2019. Generated by "Privacy
            Policy Template Generator" (https://getterms.io)
          </Text>
          <TouchableOpacity
            style={styles.button}
            onPress={() => this.props.navigation.navigate("Login")}
          >
            <Text style={styles.buttonText}>Go Back to Login Screen</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center"
  },
  subheaderText: {
    marginTop: 20,
    paddingTop: 30,
    color: "#0b409c",
    fontSize: 25,
    textAlign: "center"
  },
  policyText: {
    marginTop: 5
  },
  button: {
    color: "#ffffff",
    marginTop: 20,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#0b409c"
  }
});
